spring.application.name=salary-management

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/salary_management?reWriteBatchedInserts=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1795}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=${PORT:8080}

springdoc.swagger-ui.path=/swagger-ui.html

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:*}

logging.level.com.incubyte.salarymanagement=INFO
